### ISSUE TITLE
OS X support?

### ISSUE THREAD

**Issue by zachallaun** [showjean/ps2avrU#1]
Hi there,

Is there a build of your boot loader for OS X? I spent some time reading your site, but I unfortunately cannot read Korean and Google Translate isn't quite good enough :).

Thank you for your help!

**Comment by showjean** [comment]
link : http://winkeyless.kr/16
file : ps2avrU_bootloader_source_130722.zip
folder : commandline

need compile for OS X (I try, but failed ^^)

**Comment by zachallaun** [comment]
Thank you! I'll try to get it compiled today and will post steps here if I succeed.

In the meantime I've written up an explanation of using the hardware remapper here: http://geekhack.org/index.php?topic=40501.msg1229605#msg1229605
