### ISSUE TITLE
More keys in Dual Action function?

### ISSUE THREAD

**Issue by alan0ford** [showjean/ps2avrU#10]
Hi, in a future release it is possible to add more keys in Dual Action function?
I would like to set ArrowUp and RightShift in a dual action... Thank you! :)

Second question: is possible compile and flash the firmware on a Pro Micro (with ATmega32U4)?

**Comment by showjean** [comment]
Hello

1. Please, Check this topic.
http://winkeyless.kr/forums/topic/bootmapper-dual-action-function/

2. No

Sorry my poor english.

Thank you.

**Comment by alan0ford** [comment]
Thank you for your work, and happy 2018!
