### ISSUE TITLE
LED always automatically turns on after PC wakes up from sleep

### ISSUE THREAD

**Issue by anjari** [showjean/ps2avrU#12]
I'm using firmware ps2avrGB V1.4.0 on my keyboard, I had set up the Full LED Mode to "On" with Bootmapper Client v0.10.0. I also set up a shortcut key FN + N to "LED on/off".

I usually turn off the keyboard LED when I'm not using it with FN+ N shortcut. One day with the LED is turned off, I put my PC into sleep/hibernate state and when the PC woke up from sleep/hibernate, the LED is automatically turned on, and I had to press FN + N twice to turn off the LED.

This is probably a bug that the firmware can't remember the last on/off state of the LED after the PC wakes up from sleep.

**Comment by showjean** [comment]
Thank you for your feedback.

I will check that.

Thank you.

**Comment by anjari** [comment]
Any update about the fix?

**Comment by showjean** [comment]
I fixed it.

I attach for you beta firmware before release.

Thank you.

[ps2avrGB_20190713.zip](https://github.com/showjean/ps2avrU/files/3387613/ps2avrGB_20190713.zip)

**Comment by anjari** [comment]
I have tested the ps2avrGB_20190713 firmware for couple of days. The hibernate's LED issue is fixed, but now there is new issue shows up: sometimes when I start up my PC, the keyboard LED automatically turns on. I had made sure I had turned off the LED before I shut down my PC.

**Comment by showjean** [comment]
"LED on/off" key is not memorable. it is always 'on(default)' when keyboard power on. 
You can use shortcut for LED mode changing.
Switch LED: ESC + Capslock
RGB LED: Shift + ESC + Capslock

**Comment by anjari** [comment]
I did set a shortcut for that, but I only use the LED occasionally, and some people might have backlit mechanical keyboard but for certain reason they don't use the LED and put non-translucent keycaps. It will be annoying to see the LED turns on when the PC starts for these people. So I think it's better to set the LED "off" by default when the keyboard is powered on.

**Comment by showjean** [comment]
OK. I will consider the function.

**Comment by showjean** [comment]
Update new firmware and bootmapper.

https://github.com/showjean/ps2avrU/releases/tag/V1.5.0

You can find 'LED on/off at Power On' in Options Tab.

Thank you.

**Comment by anjari** [comment]
Thank you for the update.

---------

I also want to report a small bug in Bootmapper (I'm using the latest version), the character "\\" is incorrectly shown as "₩" (won) symbol: https://i.imgur.com/NByHAsv.jpg

**Comment by showjean** [comment]
Thank you for report.
I will check it.
