### ISSUE TITLE
PCB Guide and/or Reference Design

### ISSUE THREAD

**Issue by equalunique** [showjean/ps2avrU#13]
This is an interesting firmware that I would like to try out with some project ideas, but unless I am mistaken, there is not a guide for creating & programming a ps2avr PCB.  A reference design for a ps2avr PCB would also be a helpful starting point. Do resources like these exist? If not, can someone involved with the project please create them?

**Comment by showjean** [comment]
circuit?
https://github.com/showjean/ps2avrU/blob/master/firmware/ps2avrGB/Circuit/ps2avrGB/20140829_140848_001.png

Diode direction of switch : ROW --|>|-- COL
