### ISSUE TITLE
keyboard recognition in BIOS, in GRUB and 'wake from suspend'

### ISSUE THREAD

**Issue by VanLaser** [showjean/ps2avrU#2]
Hello,

First, thank you for working on this! The text-only key mapping feature is really great.

There are problems using ps2awrU firmware with some faceU replica boards, namely:
- BIOS keyboard recognition at computer power up
- keyboard recognition for GRUB
- no wake-up from suspend/sleep

Do you know of any cause/solution? Is it ps2avrU related? Can one build a non NKRO, e.g. a (simpler) 6KRO firmware that works without issues? Thank you.

(src thread: http://deskthority.net/workshop-f7/face-u-mx-mini-u-replica-knowledge-base-t8689.html)

**Comment by showjean** [comment]
thank you for using.

this firmware is 6KRO at USB interface. (PS/2 only NKRO)

so, My PC and MACbook recognize this keyboard at computer power up.

but, GRUB was not test.

and, wake-up from suspend/sleep is not supported.

thank you.

이용해 주셔서 감사합니다.

이 펌웨어는 USB 연결시 6KRO로 작동합니다. (PS/2에서만 NKRO)

그래서, 제 PC와 맥북에서는 컴퓨터를 켤 때 키보드를 인식합니다.

그러나, GRUB에서는 테스트해보지 못했습니다.

그리고, 절전모드에서 wake-up은 지원되지 않습니다.

감사합니다.

**Comment by VanLaser** [comment]
Thank you for answering!
Yes, the problem seems to be only in some cases ("cold boot"), probably when computer boots before firmware is loaded on keyboard (if this does make sense). Is it hard (in theory) to implement wake-up from suspend/sleep?

**Comment by showjean** [comment]
After BIOS keyboard recognition at computer power up has a few delay(about 1sec). maybe, I think, your POST message was gone before this time.
I am looking for solution about wake-up. but, I can't until now.

BIOS 키보드로 인식 된 후 약간의 딜레이(약 1초)가 있습니다. 아마도, POST 메세지가 이 딜레이가 끝나기 전에 사라진 것이 아닌가 하는 생각이 듭니다.
wake-up에 대해서는 해결책을 찾고 있지만, 아직 해결하지 못했습니다.

**Comment by VanLaser** [comment]
I understand - thank you again for answer (and for your work)!
