### ISSUE TITLE
Skipping keys in OSX

### ISSUE THREAD

**Issue by azhang** [showjean/ps2avrU#3]
Hello,
I recently acquired Sprit's FaceW pcb, running ps2avrU. 
I'm getting some issues on Mac OSX (tested on yosemite hackintosh, mavericks hackintosh, yosemite macbookpro. works on windows 7 and in bios). It was working fine until a few days ago, when it started to skip keys. Replugging fixed it. However yesterday, even that fix stopped working. Keypresses are now out of order, repeated incorrectly (eg. typig "hello" quickly sometimes -> "ehlo"), or plainly skipped whenever I type faster than ~20 wpm.

I've tried swapping usb cables, adding a powered usb hub, changing computers, resetting keymap, flashing both GKP and NKRO firmwares.

Any ideas on how to fix this?

**Comment by showjean** [comment]
Hello.

Thank you for report.

I will try to debug.

Thank you ^^

**Comment by azhang** [comment]
Thank you so much for this great project!

**Comment by azhang** [comment]
At first, when I first updated to [ps2avrU_firmware_V1.7_150215.zip](http://blog.winkeyless.kr/attachment/cfile2.uf@271BAE3E54E03CD4053D5E.zip), it had the same problems as before. But once I replugged while holding down "u" key, it started working! I tried it because I saw 

> - V1.6에서 V1.7로 업데이트 하는 경우에는 USB 드라이버가 다시 설치되는 과정이 필요하니 인식이 잘 안 될 경우 "U"키를 누른 상태로 플러깅해서 사용하시길 바랍니다.
>   translated as 
> - If you are updating from V1.6 to V1.7 If you do need to re-install the USB driver is aware of course that is not easily used by plugging Please hold down the "U" key.

I don't really understand the translation - what happens when I plug in the keyboard when holding down the "U" key?

Anyways, **thank you so much!**

**Comment by flashteker** [comment]
Hi Aaron
Thanks for your interests in our SW.
- Connecting keyboard to PC while holding down "U" key means you set keyboard connection mode to USB.
- "P" means "PS/2"
- "P" + "U" for "Resetting"

**Comment by azhang** [comment]
Thanks a lot!
