### ISSUE TITLE
How to turn off leds without an FN key?

### ISSUE THREAD

**Issue by kaansoral** [showjean/ps2avrU#5]
Hi

I don't have a key left for FN, I mapped all keys to other things, is there a way for me to turn off leds now? (maybe with a specific .hex file that manually overrides the led setting?)

Thanks in Advance

**Comment by kaansoral** [comment]
I ended up creating a keymap just for turning the leds on/off

It might be a good idea to add it as a master override combo, like hold 5 buttons for 5 seconds etc.

**Comment by showjean** [comment]
Hi

LED mode changing : ESC + Capslock

**Comment by kaansoral** [comment]
Yes, but if the CapsLock is mapped to RCtrl for example, it doesn't work, there is no space in my layout for a CapsLock or an fn-layer that will house a CapsLock - so there is no shortcut available for leds

**Comment by showjean** [comment]
If you want to change CapsLock key. redefine LED_KEY.

https://github.com/showjean/ps2avrU/blob/master/source/fncontrol.h#L9

#define LED_KEY                 KEY_CAPS
