### ISSUE TITLE
Cherry Mx lock Support

### ISSUE THREAD

**Issue by Icaruis** [showjean/ps2avrU#6]
Hi, 
Was wondering if there is MX lock support, I was hoping to have A Mx lock switch for caps lock and maybe num and scroll lock. But I'm unsure if the firmware supports the toggle-able functionality? There may be a workaround within the macro function but I am unsure. Info on the Mx lock: 
https://deskthority.net/wiki/Cherry_MX_Lock

The problem is that If I leave the firmware as is, the Mx lock when in down position(switch activated) the signal will keep firing, aka If I put a MX lock on caps lock and press it down, it was continuously per second switch caps lock on and off.

Thanks,
 Alex

**Comment by showjean** [comment]
Support for MX LOCK switch is not currently planned, let us consider in the future.

MX LOCK 스위치의 지원은 현재 계획이 없지만, 앞으로 고려해 보겠습니다.
