### ISSUE TITLE
Fn not recognized in combination inputs

### ISSUE THREAD

**Issue by ClaudiaJ** [showjean/ps2avrU#7]
# Test Setup:

FW: ps2avrU_firmware_V1.7_160228; keymain_NKRO.hex
W, A, S, D on Fn layer is mapped to Up, Left, Down, and Right
Fn key is mapped
# Problem

Fn Key is not recognized in chord combinations unless you release all other keys first, then press Fn, then press necessary modifiers again.
## Test 1: Arrow through Alt+Tab

Alt+Tab to bring up window selection grid in Windows
While Alt is still held, hold Fn and move with WASD as arrow keys.
### Actual

Fn key is not recognized. Window selection grid disappears.
### Expected

Alt+Tab window remains on screen while Alt is held, Fn+WASD moves current position indicator in grid similar to Arrow keys.
## Test 2: Move cursor word-wise
1. Type any sentence in any text editor.
2. At the end of a word, hold Ctrl+Fn and press A
### Actual

If Ctrl is held before Fn, Input is treated as Ctrl+A and selects all text.
### Expected

If both Ctrl and Fn are held while A is pressed, input should be treated as Ctrl+Left
Cursor should move one complete word in left direction.

**Comment by showjean** [comment]
Thank you for your feedback.

I will do patch it at next version.

Thanks.

**Comment by showjean** [comment]
Fixed it.
Thank you.
