### ISSUE TITLE
Can not map F13-F24

### ISSUE THREAD

**Issue by vuribe1221** [showjean/ps2avrU#9]
The F13-F24 keys are available in keymaps.h but can not be set by the bootmapper client.

**Comment by showjean** [comment]
[keyindex.zip](https://github.com/showjean/ps2avrU/files/1496218/keyindex.zip)

Replace attached file 'keyindex.json' in json folder of Bootmapper Client after unzip.

You can find F13~F26 key at bottom side on keymap tab.

Thank you.

**Comment by vuribe1221** [comment]
Perfect, thanks.
